ICJK/Home/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'Home'

urlpatterns = [
    path('', views.index),
    path('personal', views.personal),
    path('commercial', views.commercial),
    path('personal/<int:db_id>', views.personalCarView, name="personal"),
    path('commercial/<int:db_id>', views.commercialCarView, name="commercial")
]

ICJK/ICJK/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('Staff.urls'), name='Staff'),
    path('/', include('Home.urls'), name='Home'),
    path('', include('Home.urls'), name='Home'),
]

ICJK/Staff/urls.py
from django.urls import include, path, re_path
from . import views

app_name = "Staff"

urlpatterns = [
    re_path(r'^login/.*$', views.login_view, name="login"),
    path('create/', views.create, name="create"),
    path('auth/', views.auth, name="auth"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.landing_view, name="landing"),
    path('landing/', views.landing_view, name="landing"),
    path('priority/', views.priority_purchase_view, name="priority"),
    path('logistics/', views.logistics_view, name="logistics"),
    path('logistics_ajax/', views.logistics_ajax, name="logistics_ajax"),
    path('geo/',views.geo_view, name="geo")
]

ICJK/Staff/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from .StaffAccountCreationForm import StaffAccountCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from .AuthResult import AUTH_RESULT
from django.db.models import Q, Max, F
from Home.models import Car, Order, Store
from Home.views import get_latest_order_for_car

def get_purchase_statistics(store):
    query_result = []
    db_query = Q(~Q(make_name__icontains="null") & ~Q(model__icontains="null"))

    # get orders for selected store
    # car could also be somewhere else; annotate doesn´t work
    # get orders for selected store
    db_query_help = Q()
    orders = Order.objects.filter(fk_return_store_id = store)
    # filter for cars which have been ordered in selected store
    for ord in orders:
        if str(get_latest_order_for_car(ord.fk_car_id).fk_return_store_id.id) == str(store):
            #add cars which last location was store to query
            db_query_help |= Q(id = ord.fk_car_id.id)
    #add help query to main query
    db_query &= db_query_help

    query_set = Car.objects.filter(db_query).order_by('make_name', 'model', 'series')

    #build result
    for car in query_set:
        timeStore = 0
        time = 0
        ord = Order.objects.filter(fk_car_id = car.id)
        for o in ord:
            time += (o.return_date - o.pickup_date).days
            if str(o.fk_pickup_store_id.id) == store or str(o.fk_return_store_id.id) == store:
                timeStore += (o.return_date - o.pickup_date).days

        query_result.append(
        {"id":car.id,
         "name": ("%s %s %s"%(car.make_name.title(), car.model.title(), car.series.title())),
         "total": "Rented for %i days in total."%(time),
         "store": "Rented for %i days in selected store."%(timeStore),
         "orders": "Was ordered %i time(s)."%(len(ord)),
         "avg": "The average renting time is %i days." %(time/len(ord)),
         "profit": "The total profit is %i$."%((time*(car.price_new/500)-car.price_new)),
         # "link": "%s/%i"%(viewtype,car.id)
         # "link": "todo"
         })
    return query_result

# Create your views here.
@login_required(login_url='Staff:login')
def priority_purchase_view(request):

    #get value for store
    store = request.GET.get('store', None)

    #init db_query and query result
    query_result = get_purchase_statistics(store)

    #select storelist for dropdown
    storelist = Store.objects.all().filter(~Q(name__icontains="null")).order_by("name")

    if (store != None):
        store = int(store)

    return render(request, "Staff/priority_purchase.html", {
        "appname": "ICJK Car Rentals - Priority Purchase Report",
        "applink": "http://" + get_current_site(request).domain + "/",
        "carlist": query_result,
        "storelist": storelist,
        "selected_store": store,
    })

@login_required(login_url='Staff:login')
def logistics_view(request):
    store_list = [
        store.name for store in Store.objects.filter(~Q(name__icontains="null"))
    ]

    store_list = sorted(store_list)

    return render(request, "Staff/logistics.html",{
        "stores": store_list,
        "dyn_update_url": "http://" + get_current_site(request).domain + reverse("Staff:logistics_ajax"),
        "applink": "http://" + get_current_site(request).domain + "/",
        "appname": "ICJK Car Rentals - Rental Trends"
    })

def get_orders_from_store(start, end, filter_same):
    if start == end and start != "Anywhere":
            filter_same = False

    db_query = Q()
    if start != "Anywhere":
        store = Store.objects.filter(Q(name__iexact=start))[0]
        db_query &= Q(fk_pickup_store_id=store.id)

    if end != "Anywhere":
        store = Store.objects.filter(Q(name__iexact=end))[0]
        db_query &= Q(fk_return_store_id=store.id)

    if filter_same:
        db_query &= ~Q(fk_pickup_store_id=F('fk_return_store_id'))
        
    db_query &= ~Q(Q(fk_car_id__make_name__icontains="null") | Q(fk_car_id__model__icontains="null"))

    return Order.objects.filter(db_query).order_by("fk_customer_id__name").all()[:100]

@login_required(login_url='Staff:login')
def logistics_ajax(request):
    if request.method == 'GET':
        start = request.GET.get("start","Anywhere")
        end = request.GET.get("end","Anywhere")
        useFilter = False if request.GET.get("useFilter",False) in (False, 'false') else True

        results = get_orders_from_store(start, end, useFilter)

        return JsonResponse({"orders":
            [
                {
                    "purchaser":"%s"%(order.fk_customer_id.name),
                    "address":"%s"%(order.fk_customer_id.address),
                    "begin":"%s, %s, %s"%(order.fk_pickup_store_id.address, order.fk_pickup_store_id.city, order.fk_pickup_store_id.state),
                    "begindate":"%s"%(order.pickup_date),
                    "end":"%s, %s, %s"%(order.fk_return_store_id.address, order.fk_return_store_id.city, order.fk_return_store_id.state),
                    "enddate":"%s"%(order.return_date),
                    "car":"%s %s %s %s"%(order.fk_car_id.series_year,order.fk_car_id.make_name, order.fk_car_id.model, order.fk_car_id.series),
                    "carlink": "http://" + get_current_site(request).domain + reverse("Home:personal", kwargs={'db_id':order.fk_car_id.id})
                } for order in results
            ]
        }, safe=False)


def login_view(request):
    createform = StaffAccountCreationForm()
    authform = AuthenticationForm()
    return render(request, "Staff/login.html", {
        "createform": createform,
        "authform": authform,
        "applink": "http://" + get_current_site(request).domain + "/",
        "appname": "ICJK Car Rentals"
    })

@login_required(login_url='Staff:login')
def landing_view(request):
    return render(request, "Staff/landing.html", {
        "applink": "http://" + get_current_site(request).domain + "/",
        "appname": "ICJK Car Rentals"
    })

def auth(request):
    if request.method == 'POST':
        authform = AuthenticationForm(data=request.POST)
        if authform.is_valid():
            user = authform.get_user()
            return log_in_and_send_to_next(request, user)
        else:
            return redirect(reverse('Staff:login') + '/?result=%i&view=0'%AUTH_RESULT.LOGIN_INVALID_COMBINATION.value)
    else:
        return redirect(reverse('Staff:login') + '/?result=%i&view=0'%AUTH_RESULT.LOGIN_OTHER.value)

def create(request):
    if request.method == 'POST':
        form = StaffAccountCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return log_in_and_send_to_next(request, user)
        else:
            error = form.previous_error
            return redirect(reverse('Staff:login') + '/?result=%i&view=1'%error.value)

def log_in_and_send_to_next(request, user):
    login(request, user)
    if(request.POST.get("next", None) is not None):
        return redirect(request.POST.next)
    return redirect("Staff:landing")

def logout_view(request):
    try:
        logout(request)
    except Exception:
        pass
    finally:
        return redirect(reverse('Staff:login'))

@login_required(login_url='Staff:login')
def geo_view(request):
    
    storelist = Store.objects.all().order_by("name")
    
    
    return render(request, "Staff/geo.html",{
        "applink": "http://" + get_current_site(request).domain + "/",
        "appname": "ICJK Car Rentals",
        "storelist": storelist,

    })

ICJK/Staff/templates/Staff/base_template.html
<html lang="en">
<head>
        <title>{{ appname }}</title>

        {% block stylesheet %}
        {% endblock %}
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <nav class="nav-extended deep-orange accent-4">
        <div class="nav-wrapper">
            <a href="{{ applink }}" class="brand-logo nav_title">{{ appname }}</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">

                {% block nav_bar_desktop %}
                <!-- When you make a new staff page, add a link to it here so it is put on all of the other staff pages' navigation bars -->
                <li><a href="{% url 'Staff:landing' %}">Staff Home</a></li>
                <li><a href="{% url 'Staff:priority' %}">Priority Purchase Report</a></li>
                <li><a href="{% url 'Staff:logistics' %}">Rental Trends</a></li>
                <li><a href="{% url 'Staff:geo' %}">Store Map</a></li>
                {% endblock %}
                <li><a href="{% url 'Staff:logout' %}">Logout</a></li>
            </ul>
        </div>
    </nav>
    <ul class="sidenav" id="mobile-demo">
            <!-- When you make a new staff page, add a link to it here so it is put on all of the other staff pages' navigation bars -->
            {% block nav_bar_mobile %}
            <li><a href="{% url 'Staff:landing' %}">Staff Home</a></li>
            <li><a href="{% url 'Staff:priority' %}">Priority Purchase Report</a></li>
            <li><a href="{% url 'Staff:logistics' %}">Rental Trends</a></li>
            <li><a href="{% url 'Staff:geo' %}">Store Map</a></li>
            {% endblock %}
            <li><a href="{% url 'Staff:logout' %}">Logout</a></li>
    </ul>


    {% block page_content %}

    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block javascript %}
    {% endblock %}
    <script type="text/javascript">
        $(document).ready(function(){
            $('.sidenav').sidenav();
        });
    </script>
</body>

ICJK/Staff/templates/Staff/geo.html
{% extends "Staff/base_template.html" %}

{% block stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static 'Staff/index.css' %}">
{% endblock %}

{% block javascript %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyChkL1-v3Cgf3zc1BfNFucXnovUyZsRiBQ&callback=initMap"
async defer></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    
var map;

function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: -26, lng: 134.644},
    zoom: 5
    });
    
    stores.forEach(address => geocode(address[0]))
}

  

function geocode(location){
axios.get('https://maps.googleapis.com/maps/api/geocode/json',{
    params:{
        address:location,
        key:'AIzaSyChkL1-v3Cgf3zc1BfNFucXnovUyZsRiBQ'
     }
    })
    .then(function(response){
        const loc = response.data.results;
        const {lng, lat} = loc[0].geometry.location;

        new google.maps.Marker({
            position: {lat: lat, lng: lng},
            map: this.map
        })
    })
    .catch(function(error){
    console.log(error);
    });
   

}  



</script>
{% endblock %}

{% block page_content %} 

    {% if storelist %}
        <script>const stores = new Set();</script>
        {% for store in storelist %}
            <script>
                //geocode('{{store.city}} , {{store.state}}')
                //console.log('{{store.city}} , {{store.state}}')
                stores.add(['{{store.city}}, {{store.state}}'])
            </script>
             
        {% endfor %}
    {% endif %}
    
    <div id="map"></div>
    
    
{% endblock %}

ICJK/Staff/templates/Staff/index.html
<html lang="en">
<head>
        <title>{{ appname }}</title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'Staff/index.css' %}">

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <nav class="nav-extended deep-orange accent-4">
        <div class="nav-wrapper">
            <a href="{{ applink }}" class="brand-logo nav_title">{{ appname }}</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
            </ul>
        </div>
    </nav>

    <div class="centralise">
        <div class="row">
            <div class="col s0 l3"></div> <!-- For positioning -->
            <div class="col s12 l6">
                <div class="card-panel">
                    <h4>Staff Login</h4>
                    <div class="row">
                        <div class="input-field col s12">
                            <input id="staff_username" type="text" class="validate">
                            <label for="first_name">Staff Username</label>
                        </div>
                        <div class="input-field col s12">
                            <input id="password" type="password" class="validate">
                            <label for="password">Password</label>
                        </div>
                        <div class="input-field col s6">
                            <a class="waves-effect waves-light btn">Login</a>
                        </div>
                        <div class="input-field col s6">
                            <a class="waves-effect waves-light btn">Create Account</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script src="{% static 'Staff/index.js' %}"></script>
</body>

ICJK/Staff/templates/Staff/landing.html
{% extends "Staff/base_template.html" %}

{% block stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static 'Staff/index.css' %}">
{% endblock %}

{% block nav_bar_desktop %}
{% endblock %}

{% block nav_bar_mobile %}
{% endblock %}

{% block page_content %}
    <div class='container'>

        <div class="row">
            <div class="col s1"></div>
            <div class="col s10 card">
                <ul class="collection with-header">
                    <li class="collection-header"><h2>Staff Home</h2><p>Logged in as {{user.get_username}}</p></li>

                    <li class="collection-item"><a href="{% url 'Staff:priority' %}">Priority Purchase Report</a><div class="secondary-content grey-text">View rental statistics for each car in stock.</div></li>
                    <li class="collection-item"><a href="{% url 'Staff:logistics' %}">Rental Trends</a><div class="secondary-content grey-text">Inspect orders to find rental trends between stores.</div></li>
                    <li class="collection-item"><a href="{% url 'Staff:geo' %}">Store Map</a><div class="secondary-content grey-text">See a map of all ICJK Car Rental stores.</div></li>
                </ul>
            </div> 
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'Staff/landing.js' %}"></script>
{% endblock %}

ICJK/Staff/templates/Staff/login.html
<html lang="en">
<head>
        <title>{{ appname }}</title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'Staff/index.css' %}">

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <nav class="nav-extended deep-orange accent-4">
        <div class="nav-wrapper">
            <a href="{{ applink }}" class="brand-logo nav_title">{{ appname }}</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
            </ul>
        </div>
    </nav>

    <div class="row">
        <div class="col m0 l3"></div> <!-- For positioning -->
        <div class="col m12 l6">
            <div class="card">
                <div class="card-content">
                    <h4>Staff Login</h4>
                </div>
                <div class="card-tabs">
                    <ul class="tabs tabs-fixed-width">
                        <li id="login_tab" class="tab"><a href="#login">Login</a></li>
                        <li id="create_tab" class="tab"><a class="active" href="#create">Create</a></li>
                    </ul>
                </div>
                <div class="card-content grey lighten-4">
                    <div id="login">
                        <form action="{% url 'Staff:auth' %}" method="POST">
                            {% csrf_token %}
                            {{ authform }}
                            {% if request.GET.next %}
                            <input type='hidden' name='forward' value="{{request.GET.next}}">
                            {% endif %}
                            <button class="btn waves-effect waves-light" type="submit" name="action">Login</button>
                        </form>
                    </div>
                    <div id="create">
                        <form action="{% url 'Staff:create' %}" method="POST">
                            {% csrf_token %}
                            {{ createform }}
                            <ul>
                                <li>Your password can't be too similar to your email address.</li>
                                <li>Your password must contain at least 8 characters.</li>
                                <li>Your password must contain at least one numeric, and one alphabet character.</li>
                            </ul>
                            {% if request.GET.next %}
                            <input type='hidden' name='forward' value="{{request.GET.next}}">
                            {% endif %}
                            <button class="btn waves-effect waves-light" type="submit" name="action">Create Account</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'Staff/login.js' %}"></script>
</body>

ICJK/Staff/templates/Staff/logistics.html
{% extends "Staff/base_template.html" %}

{% block stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static 'Staff/index.css' %}">
{% endblock %}

{% block page_content %}
<div class='container'>
    <div class="row">
        <div class="col s12">
            <div class="card white hoverable">
                <div class="card-content black-text">
                    <span class="card-title">Rental Trends</span>
                    <div class="row">
                        <table>

                            <tr><td>Starting at:</td><td><a id="starting-dropdown" class='dropdown-trigger btn red' href='#' data-target='starting-location'> Anywhere </a></td>

                            <tr><td>Finishing at:</td><td><a id="ending-dropdown" class='dropdown-trigger btn red' href='#' data-target='ending-location'> Anywhere </a></td>


                            <tr><td>Only show orders that have differing start and end stores: </td><td>
                                <div class="switch">
                                    <label>
                                        Show All
                                        <input id="filterToggle" type="checkbox" onclick="toggleFilter()">
                                        <span class="lever"></span>
                                        Show Only Different
                                    </label>
                                </div>
                            </a></td>
                            
                        </table>
                    </div>


                    <ul id='starting-location' class='dropdown-content'>
                        <li><a onclick="setStart('Anywhere')">Anywhere</a></li>
                        {% for store in stores %}
                        <li><a onclick="setStart('{{store}}')">{{store}}</a></li>
                        {% endfor %}
                    </ul>
                    <ul id='ending-location' class='dropdown-content'>
                        <li><a onclick="setEnd('Anywhere')">Anywhere</a></li>
                        {% for store in stores %}
                        <li><a onclick="setEnd('{{store}}')">{{store}}</a></li>
                        {% endfor %}
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div class="row" id="loading-box">
        <div class="col s2 offset-s5">
                <div class="lds-ripple"><div></div><div></div></div>
        </div>
    </div>
    <div class="row">
        <div class="col s12" id="result-container">

        </div>
    </div>

</div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
    function updateGraph(){
        let url = "{{dyn_update_url}}";
        clearResults();
        setLoading(true);
        $.get(url, {start:startLocation, end:endLocation, useFilter:useFilter},(response)=> {
            setTimeout(()=>{
            
            for(order of response.orders){
                addResult(order);
            }
            setLoading(false);
        }, 500, response );
    });
    }

</script>
<script src="{% static 'Staff/logistics.js' %}"></script>
{% endblock %}

ICJK/Staff/templates/Staff/priority_purchase.html
{% extends "Staff/base_template.html" %}

{% block stylesheet %}
{% load static %}
<link rel="stylesheet" href="{% static 'Staff/index.css' %}">
{% endblock %}

{% block page_content %}
<div class='container'>
    <div class="row">
        <div class="col s12">
            <div class="card white hoverable">
                <div class="card-content black-text">
                    <form method="get">
                      <div class="row">
                          <div class="input-field col s12">
                              <select name="store" id="store">
                                  <option value = "" disabled selected>Select store</option>
                                  {% if storelist %}
                                      {% for store in storelist  %}
                                        {% if store.id == selected_store %}
                                            <option value="{{store.id}}" selected>{{store.name}}</option>
                                        {% else %}
                                            <option value="{{store.id}}">{{store.name}}</option>
                                        {% endif %}
                                      {% endfor %}
                                  {% endif %}

                              </select>
                              <label for="store">Select store to see available cars</label>
                          </div>
                          <div class="col s6 m1 valign-wrapper">
                              <button class="btn-floating btn-medium waves-effect waves-light" type="submit" name="action" value="submit">
                                  <i class="material-icons right">send</i>
                              </button>
                          </div>
                          <div class="col m1 s6 valign-wrapper"">
                                <a href="/staff/priority/" class="btn-floating btn-medium waves-effect waves-light">
                                  <i class="material-icons right">clear</i>
                                </a>
                          </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>

        {% if carlist %}
            {% for car in carlist %}
                <div class="col s12">
                    <div class="card small white hoverable">
                        <div class="card-content black-text">
                            <span class="card-title">{{car.name}}</span>
                            <p>{{car.total}}</p>
                            <p>{{car.store}}</p>
                            <p>{{car.orders}}</p>
                            <p>{{car.avg}}</p>
                            <p>{{car.profit}}</p>
                        </div>
                        <!-- <div class="card-action">
                            <a href="{{car.link}}">More Details</a>
                        </div> -->
                    </div>
                </div>
            {% endfor %}
        {% else %}

        <div class="col s12">
            <div class="card white">
                <div class="card-content black-text">
                    <span class="card-title center">There are no cars here <i class="material-icons center">error_outline</i></span>
                    <p class="center">Try altering your search critera to be more general</p>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'Staff/priority.js' %}"></script>
{% endblock %}